### ISSUE TITLE
Calling the wrong function

### ISSUE THREAD

**Issue by flamusdiu** [lashex/flask-neo4j#8]
It appears that GraphDatabaseService() was replaced by Graph(). and py2neo is also 2.0.6.
```
AttributeError
AttributeError: 'module' object has no attribute 'GraphDatabaseService'

Traceback (most recent call last)
File "/home/jesse/.virtualenvs/flask/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/home/jesse/.virtualenvs/flask/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/home/jesse/.virtualenvs/flask/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/jesse/.virtualenvs/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/home/jesse/.virtualenvs/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/jesse/.virtualenvs/flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/jesse/.virtualenvs/flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/home/jesse/.virtualenvs/flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/jesse/Documents/git_projects/python-site/app/main/views.py", line 27, in index
user = User.create(user_profile)
File "/home/jesse/Documents/git_projects/python-site/app/user/models.py", line 23, in create
db.gdb.create(node)
File "/home/jesse/.virtualenvs/flask/lib/python2.7/site-packages/flask_neo4j.py", line 99, in gdb
self.graph_db = neo4j.GraphDatabaseService()
AttributeError: 'module' object has no attribute 'GraphDatabaseService'
```

**Comment by flamusdiu** [comment]
v.0.4.0 wasn't in `pip`. I had to update it through git-hub.
